### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by callmehiphop**

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Looks like if you updated main `package-lock.json`, you also need to update the one from samples, otherwise samples' `npm install` fails for some reason. We're still learning how to live with that :)

Can you try running 
```sh
rm -rf node_modules samples/node_modules package-lock.json samples/package-lock.json
npm install && npm link && cd samples && npm link ../ && npm install && cd .. 
```
and then add both `package-lock.json` and `samples/package-lock.json` to this PR?

**Comment by callmehiphop** [comment]
@alexander-fenster seems to have done the trick!

**Comment by alexander-fenster** [comment]
@callmehiphop Dave, may I ask you to do the same trick once more to regenerate lock files? I pushed one more change to master (#18) and now this PR cannot be merged. When you update the lock files, feel free to draft a release of the latest master. Thanks!

**Comment by alexander-fenster** [comment]
Nevermind, I was able to resolve conflicts using GitHub web editor :)

**Comment by alexander-fenster** [comment]
Nope, it's still bad. Looks like I cannot fix it properly in your repo - can you still regen the lock files please? :) @callmehiphop

**Comment by alexander-fenster** [comment]
OK - I found out I can update your repo, so here we go! :)

**Pull request merged**
